### ISSUE TITLE
Bug: Dark mode feature 

### ISSUE THREAD

**Issue by joelibaceta** [joelibaceta/gh-tl#3]
<img width="632" alt="Captura de Pantalla 2020-03-07 a la(s) 03 31 00" src="https://user-images.githubusercontent.com/864790/76140009-1542a600-6024-11ea-8f43-926ad737e572.png">

<img width="1027" alt="Captura de Pantalla 2020-03-07 a la(s) 03 30 16" src="https://user-images.githubusercontent.com/864790/76139999-03610300-6024-11ea-8e2e-6ae34d2c849a.png">

**Comment by joelibaceta** [comment]
@lewyuburi could you check this?

**Comment by lewyuburi** [comment]
> @lewyuburi could you check this?

Done. #4

**Comment by joelibaceta** [comment]
Thanks @lewyuburi for your contribution
